[package]
authors = ["Max Gubin <max@gubin.info>"]
edition = "2024"
license = "MIT"
name = "pool-controller"
version = "0.1.0"

[dependencies]
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver"] }
log = { version = "0.4", default-features = false }
embassy-time = { version = "0.5", features = ["generic-queue-16"] }

[build-dependencies]
embuild = { version = "0.33", features = ["espidf"] }

[profile.dev]
opt-level = 's'

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 's'
overflow-checks = false
panic = 'abort'
rpath = false
strip = "symbols"
